FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt requirements-test.txt ./

RUN pip install --no-cache-dir -r requirements.txt \
 && pip install --no-cache-dir -r requirements-test.txt

# Copia o conteúdo da pasta app diretamente para dentro do container
COPY ./app .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
