[pytest]
testpaths = app/tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = 
    -v
    --tb=short
    --strict-markers
    --cov=app/domain           
    --cov=app/application      
    --cov-report=html
    --cov-report=term-missing
    --cov-fail-under=60

markers =
    unit: Testes unitários rápidos
    integration: Testes de integração
    slow: Testes lentos
    db: Testes que usam banco de dados
    critical: Testes críticos

filterwarnings =
    ignore::DeprecationWarning

[coverage:run]
omit = 
    */tests/*
    */conftest.py
    */__init__.py
    */migrations/*

[coverage:report]
precision = 2
show_missing = True
skip_covered = False